server:
  port: 8085

spring:
  application:
    name: notification-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: techshop_notifications
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-service
      auto-offset-reset: earliest
  mail:
    host: localhost
    port: 1025
    username: ""
    password: ""

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    com.techshop: DEBUG