server:
  port: 8082

spring:
  application:
    name: order-service
  cloud:
    config:
      enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/techshop
  datasource:
    url: jdbc:postgresql://localhost:5432/techshop_order
    username: techshop
    password: techshop
    driver-class-name: org.postgresql.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
  kafka:
    bootstrap-servers: localhost:9092
    topics:
      order-events: order-events
      payment-commands: payment-commands
      payment-results: payment-results
    consumer:
      group-id: order-service
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

logging:
  level:
    com.techshop: DEBUG
